import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full">
          <div className="container mx-auto py-5 border-b border-gray-400">
            <Link className="text-xl" href="/">
              Rick and Morty GQL
            </Link>
          </div>
        </header>
        <main className="container mx-auto my-10">{children}</main>
      </body>
    </html>
  );
}
